title: "Ken Elwell's AI Collection"
description: "Exploring AI through Lo-Fi AI discographies, Tic-Tec projects, and B-Side explorations."
theme: jekyll-theme-minimal
baseurl: "/RAG-Project-Workbooks"  # <== Add this line to match your repository name
url: "https://k3lw3ll.github.io"
permalink: pretty

# Enable navigation links
header_pages:
  - index.md
  - lo-fi-ai.md
  - tic-tec.md
  - tec-tools.md
  - b-sides.md
  - about.md
